version: "3"

services:

  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: cuckoo
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./data-postgres:/var/lib/postgresql/data/pgdata

  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./data-mongo:/data/db

  elasticsearch:
    image: elasticsearch:5.6
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - ./data-elasticsearch:/usr/share/elasticsearch/data